theme: jekyll-theme-cayman
title: مقررات و مرامنامه گروه چابک ایران
description: از اینکه به ما در گروه بحث و گفتگوی انجمن چابک پیوسته‌اید بسیار خرسندیم. لطفاً قبل از فعالیت در گروه تلگرامی، قواعد و مرامنامه زیر را با دقت مطالعه کنید. به علت اهمیت فضای مثبت گروه، تلاش می‌کنیم این قواعد همواره شفاف، روشن و به‌روز باقی بمانند.
github:
  is_project_page: false
